import { RouteInfo } from "./horizontal-sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Consentimiento",
    icon: "icon-speedometer",
    class: "has-arrow",
    ddclass: "",
    extralink: false,
    submenu: [
      {
        path: "/dashboard/dashboard1",
        title: "Consulta",
        icon: "mdi mdi-adjust",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/dashboard/dashboard2",
        title: "Pago a Establecimientos",
        icon: "mdi mdi-adjust",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Notificación",
    icon: "ti-layout-media-right-alt",
    class: "has-arrow",
    ddclass: "two-column",
    extralink: false,
    submenu: [
    ],
  },
  {
    path: "",
    title: "Configuración",
    icon: "ti-layout-grid2",
    class: "has-arrow",
    ddclass: "two-column",
    extralink: false,
    submenu: [
      {
        path: "/apps/chat",
        title: "Conexiones",
        icon: "mdi mdi-comment-processing-outline",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/todo",
        title: "Enmascaramiento",
        icon: "mdi mdi-clipboard-text",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/notes",
        title: "Encriptación",
        icon: "mdi mdi-arrange-bring-forward",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/mail/inbox",
        title: "Certificado Dígital",
        icon: "mdi mdi-inbox",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/users",
        title: "Información General",
        icon: "mdi mdi-account-multiple",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/usersrxjs",
        title: "Corte de Carga",
        icon: "mdi mdi-account-multiple",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/fullcalendar",
        title: "Calendario/Feriado",
        icon: "mdi mdi-calendar",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/invoice",
        title: "Ambientes",
        icon: "mdi mdi-file",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/taskboard",
        title: "Proceso",
        icon: "mdi mdi-bulletin-board",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/contact",
        title: "Errores",
        icon: "mdi mdi-account-box",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/contactrxjs",
        title: "Mensajes",
        icon: "mdi mdi-account-box",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/contact-list",
        title: "Estados",
        icon: "mdi mdi-phone-voip",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/contact-list-rxjs",
        title: "Tipo de Archivo",
        icon: "mdi mdi-phone-voip",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/apps/contact-grid",
        title: "Tipo de Registro",
        icon: "mdi mdi-phone",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Proceso Automático",
    icon: "ti-layout-accordion-merged",
    class: "has-arrow",
    ddclass: "",
    extralink: false,
    submenu: [
    ],
  },
  {
    path: "",
    title: "Seguridad",
    icon: "ti-palette",
    class: "has-arrow",
    ddclass: "mega-dropdown",
    extralink: false,
    submenu: [
      {
        path: "/component/accordion",
        title: "Usuario",
        icon: "mdi mdi-equal",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/alert",
        title: "Roles",
        icon: "mdi mdi-message-bulleted",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/carousel",
        title: "Permisos",
        icon: "mdi mdi-view-carousel",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/component/dropdown",
        title: "Logs",
        icon: "mdi mdi-arrange-bring-to-front",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
    ],
  },

      // {
      //     path: "/maps/google",
      //     title: "Google Maps",
      //     icon: "mdi mdi-google-maps",
      //     class: "",
      //     ddclass: "",
      //     extralink: false,
      //     submenu: [],
      // },
];
