import { RouteInfo } from "./vertical-sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Dashboard",
    icon: "fas fa-chart-pie",
    class: "has-arrow",
    label: "",
    labelClass: "side-badge badge badge-pill text-white bg-amarillo",
    extralink: false,
    submenu: [
      {
        path: "/dashboard/resumen",
        title: "Resumen",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      }
    ]
  },
  {
    path: "",
    title: "Configuración",
    icon: "ti-settings",
    class: "has-arrow",
    label: "",
    labelClass: "side-badge badge badge-pill text-white bg-amarillo",
    extralink: false,
    submenu: [
      // {
      //   path: "/informacion-general/informacion-general",
      //   title: "Información General",
      //   icon: "mdi mdi-adjust",
      //   class: "",
      //   label: "",
      //   labelClass: "",
      //   extralink: false,
      //   submenu: [],
      // },
      // {
      //   path: "/ambientes/ambiente",
      //   title: "Ambientes",
      //   icon: "mdi mdi-adjust",
      //   class: "",
      //   label: "",
      //   labelClass: "",
      //   extralink: false,
      //   submenu: [],
      // },
      // {
      //   path: "",
      //   title: "Conexiones",
      //   icon: "mdi mdi-adjust",
      //   class: "has-arrow",
      //   label: "",
      //   labelClass: "",
      //   extralink: false,
      //   submenu: [
      //     {
      //       path: "/conexiones/conexiones-SFTP",
      //       title: "SFTP",
      //       icon: "mdi mdi-adjust",
      //       class: "",
      //       label: "",
      //       labelClass: "",
      //       extralink: false,
      //       submenu: [],
      //     },
      //     {
      //       path: "/conexiones/conexiones-BaseDeDatos",
      //       title: "Base de Datos",
      //       icon: "mdi mdi-adjust",
      //       class: "",
      //       label: "",
      //       labelClass: "",
      //       extralink: false,
      //       submenu: [],
      //     },
      //     {
      //       path: "/conexiones/conexiones-CapaDeServicios",
      //       title: "Capa de Servicios",
      //       icon: "mdi mdi-adjust",
      //       class: "",
      //       label: "",
      //       labelClass: "",
      //       extralink: false,
      //       submenu: [],
      //     },
      //   ],
      // },

      // {
      //   path: "/errores/errores",
      //   title: "Errores",
      //   icon: "mdi mdi-adjust",
      //   class: "",
      //   label: "",
      //   labelClass: "",
      //   extralink: false,
      //   submenu: [],
      // },
      // {
      //   path: "",
      //   title: "Correo",
      //   icon: "mdi mdi-adjust",
      //   class: "has-arrow",
      //   label: "",
      //   labelClass: "",
      //   extralink: false,
      //   submenu: [
      //     {
      //       path: "/correo/ajusteservidor",
      //       title: "Ajuste de servidor",
      //       icon: "mdi mdi-adjust",
      //       class: "",
      //       label: "",
      //       labelClass: "",
      //       extralink: false,
      //       submenu: [],
      //     },
      {
        path: "/configuracion/plantillas",
        title: "Plantilla",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/configuracion/encuesta",
        title: "Encuesta",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      }, {
        path: "/configuracion/dispositivos",
        title: "Dispositivo",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      //   ],
      // },
      // {
      //   path: "",
      //   title: "Catálogos",
      //   icon: "mdi mdi-adjust",
      //   class: "has-arrow",
      //   label: "",
      //   labelClass: "",
      //   extralink: false,
      //   submenu: [
      //     {
      //       path: "/configuracion-carga/tipos-archivo",
      //       title: "Tipos de Archivo",
      //       icon: "mdi mdi-adjust",
      //       class: "",
      //       label: "",
      //       labelClass: "",
      //       extralink: false,
      //       submenu: [],
      //     },
      //     {
      //       path: "/configuracion-carga/catalogo-tipo-registro",
      //       title: "Tipo de Registro",
      //       icon: "mdi mdi-adjust",
      //       class: "",
      //       label: "",
      //       labelClass: "",
      //       extralink: false,
      //       submenu: [],
      //     },
      //     {
      //       path: "/configuracion-carga/interfaces",
      //       title: "Interfaces",
      //       icon: "mdi mdi-adjust",
      //       class: "",
      //       label: "",
      //       labelClass: "",
      //       extralink: false,
      //       submenu: [],
      //     },
      //     {
      //       path: "/configuracion-carga/tipo-cuenta",
      //       title: "Tipo de cuenta",
      //       icon: "mdi mdi-adjust",
      //       class: "",
      //       label: "",
      //       labelClass: "",
      //       extralink: false,
      //       submenu: [],
      //     },
      //     {
      //       path: "/configuracion-carga/numero-cuenta",
      //       title: "Número de cuenta",
      //       icon: "mdi mdi-adjust",
      //       class: "",
      //       label: "",
      //       labelClass: "",
      //       extralink: false,
      //       submenu: [],
      //     },
      //   ],
      // },

      // {
      //   path: "/configuracion-carga/tipos-registro",
      //   title: "Estructura de Archivo",
      //   icon: "mdi mdi-adjust",
      //   class: "",
      //   label: "",
      //   labelClass: "",
      //   extralink: false,
      //   submenu: [],
      // },
    ],
  },
  {
    path: "",
    title: "Proceso Automático",
    icon: "fas fa-tasks",
    class: "has-arrow",
    label: "",
    labelClass: "side-badge badge badge-pill text-white bg-amarillo",
    extralink: false,
    submenu: [
      {
        path: "/procesos/procesos",
        title: "Procesos",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      {
				path: "conexiones/conexiones-CapaDeServicios",
				title: "Capas de servicios",
				icon: "",
				class: "",
				label: "",
				labelClass: "",
				extralink: false,
				submenu: []
			}
    ],
  },
  {
    path: "",
    title: "Seguridad",
    icon: "fas fa-shield-alt",
    class: "has-arrow",
    label: "",
    labelClass: "side-badge badge badge-pill text-white bg-amarillo",
    extralink: false,
    submenu: [
      /*{
        path: "/usuario/usuario",
        title: "Usuario",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/roles/roles",
        title: "Roles",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },*/
      {
        path: "/permisos/permisos",
        title: "Permisos",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      /*{
        path: "/logs/Logs",
        title: "Logs",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/estructura-menu/estructura-menus",
        title: "Estructura del Menú",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "/enmascaramiento/enmascaramiento",
        title: "Enmascaramiento",
        icon: "mdi mdi-adjust",
        class: "",
        label: "",
        labelClass: "",
        extralink: false,
        submenu: [],
      },*/

    ],
  },
];
